### ISSUE TITLE
options parameter deprecated in v1.0.0 in Eel.js 

### ISSUE THREAD

**Issue by MusaKhan16** [hrdtbs/template-create-react-app-eel#1]
----------------------------------------------------------------------------------
  'options' argument deprecated in v1.0.0, see https://github.com/ChrisKnott/Eel
  To suppress this error, add 'suppress_error=True' to start() call.
  This option will be removed in future versions
----------------------------------------------------------------------------------

**Comment by hrdtbs** [comment]
💯
