### ISSUE TITLE
npm-run-all -p start: command could not be found

### ISSUE THREAD

**Issue by einfachWitzlos** [hrdtbs/template-create-react-app-eel#7]
yarn start
yarn run v1.22.15
$ npm-run-all -p start:*
Der Befehl "npm-run-all" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

(the command is either misspelled or could not be found)

I just cloned it and created a venv + installed the packages for python, then ran yarn

**Comment by hrdtbs** [comment]
It appears that `yarn start` is working correctly.
Did you run `yarn install` before running the command?

There are several Node.js package managers, including yarn, npm, and pnpm, all of which require you to first run the `install` command to install the packages you need for development.

If running `yarn install` does not work, it is most likely a bug in npm-run-all.

For more information on npm-run-all, please see the following
https://github.com/mysticatea/npm-run-all
